### ISSUE TITLE
Enchantment Disabler

### ISSUE THREAD

**Issue by AlexJoo2003** [ValentinosTeam/ValentinosTweaks#2]
This feature will manage what items on the server to **block** from manual enchantment. By manual enchantment I mean that applying an enchantment through the enchanting table should be blocked and combination of items/books to selected item also blocked. This doesn't mean that items that are already enchanted should be disenchanted nor does it mean that enchanting with commands should be blocked too.

Config example:
```yaml
tweaks:
    enchant-disabler:
        enabled: true
        items: [ 
            "ELYTRA",
            "MACE"
        ]
```

The itemTypes can be found [here](https://jd.papermc.io/paper/1.21.4/org/bukkit/inventory/ItemType.html).
